package com.javarush.entity.polymorphism;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Polymorphism;
import org.hibernate.annotations.PolymorphismType;

import javax.persistence.*;

@Entity
@DiscriminatorValue("INTERNAL")
@Polymorphism(type = PolymorphismType.EXPLICIT)  // Ключевая аннотация!
@Getter
@Setter
public class InternalNotification extends Notification {
    @Column(name = "system_component")
    private String systemComponent;

    @Column(name = "log_level")
    private String logLevel; // DEBUG, INFO, ERROR

    @Column(name = "technical_details", length = 4000)
    private String technicalDetails;

    @Column(name = "developer_only")
    private Boolean developerOnly = true;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = true;
}