# src/main/resources/app.properties
# ???? ???? ????? ????????? Maven (filtering=true)
# ??? ${...} ????? ???????? ?? ???????? ?? pom.xml

app.name=${app.name}
app.version=${project.version}
app.build.date=${maven.build.timestamp}
app.java.version=${maven.compiler.source}
app.encoding=${project.build.sourceEncoding}

# ?????? ????????????? ? ????:
# Properties props = new Properties();
# props.load(getClass().getResourceAsStream("/app.properties"));
# System.out.println(props.getProperty("app.name"));